### ISSUE TITLE
Update the grunt.template page in the API docs 

### ISSUE THREAD

**Issue by paulovieira** [gruntjs/grunt-docs#152] opened 2016-02-02 13:26 UTC
In the example for `grunt.template.today` we should see "2016" instead of "2015".

**Comment by JKAussieSkater** [comment] 2016-02-03 10:55
Duplicate of [Closed Issue # 151](https://github.com/gruntjs/grunt-docs/issues/151)

I've opened a new Issue ticket [here] (https://github.com/gruntjs/grunt-docs/issues/153) so you can track the progress of this problem.

**Closed by JKAussieSkater** 2016-02-03 10:55 UTC
Labels: duplicate
